name: mycontainer
services:
  web:
    # user: root
    image: php:8.3-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 9000:80
    networks:
      - testdb
    depends_on:
      - db  

  db:
    image: mariadb:10
    ports:
      - '9001:3306'
    networks:
      - testdb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

networks:
  testdb:
    driver: bridge
volumes:
  db_data:
    driver: local